### ISSUE TITLE
Change the mode_info color on mode change

### ISSUE THREAD

**Issue by leiserfg** [andreyorst/powerline.kak#2]
I think that will be cool if instead of removing the mode_info block when in normal, it changes the color (as in airline)

**Comment by andreyorst** [comment]
You can't change color of `{{mode_info}}` atom because it uses colors that are defined in colorscheme, and can't be colored with faces (`set-option global modelinefmt '{black,black}{{mode_info}}'` will still show mode info with colors defined in colorscheme), so you need to change current colorscheme of Kakoune. I don't think that **powerline.kak** should ever try to modify colorscheme files, because it is wrong approach and should never happen, and even if I try to do it there are situations when it just can't do that because default themes need root access to be changed.

More than that, current behavior of `{{mode_info}}` keeps the same behavior of default Kakoune's modeline, and I don't think that it should be changed with some kind of current mode parser, because It will drastically increase performance impact on slow PCs. **powerline.kak** is already not the lightest implementation of modeline, since it needs to be rebuilt on each buffer change to keep relevant modules on, and hide irrelevant modules.
